# Generated by Django 6.0.3 on 2026-06-10 10:14

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Complaint',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('complaint_iD', models.CharField(blank=True, max_length=50, unique=True)),
                ('complaint_title', models.CharField(max_length=100)),
                ('complaint_description', models.TextField()),
                ('complaint_address', models.CharField(max_length=50)),
                ('complaint_category', models.CharField(choices=[('road', 'road'), ('water', 'water'), ('electricity', 'electricity'), ('sanitation', 'sanitation')], default='road', max_length=20)),
                ('complaint_image', models.ImageField(upload_to='complaint_images/')),
                ('latitude', models.DecimalField(decimal_places=7, max_digits=10)),
                ('longitude', models.DecimalField(decimal_places=7, max_digits=10)),
                ('complaint_status', models.CharField(choices=[('pending', 'pending'), ('in_progess', 'in_process'), ('assigned', 'assigned'), ('solved', 'solved'), ('closed', 'closed')], default='pending', max_length=20)),
                ('complaint_priority', models.CharField(choices=[('low', 'low'), ('medium', 'medium'), ('high', 'high'), ('emergency', 'emergency')], default='medum', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('assignedOfficer', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='complaints_assigned', to=settings.AUTH_USER_MODEL)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='complaints_created', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
