# Generated by Django 6.0.3 on 2026-06-11 09:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('complaints', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='complaint',
            name='complaint_image',
            field=models.ImageField(blank=True, null=True, upload_to='complaint_images/'),
        ),
    ]
