# Generated by Django 6.0.3 on 2026-06-15 04:35

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Department',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dept_id', models.CharField(max_length=10)),
                ('dept_name', models.CharField(max_length=20)),
                ('dept_description', models.TextField()),
                ('is_active', models.BooleanField(default=True)),
            ],
        ),
    ]
